/**
 * LLM-assisted test generation (FR-4).
 * Calls the Anthropic API to propose higher-level journey/edge-case tests.
 * Output is *.draft.spec.ts — never auto-enabled, requires human review.
 */

import Anthropic from "@anthropic-ai/sdk";
import type { ParsedDashboard } from "./parser";
import type { GeneratedFile } from "./templates";

const ANTHROPIC_API_KEY = process.env.ANTHROPIC_API_KEY;

const SYSTEM_PROMPT = `You are a Playwright test generator for Grafana dashboards.
Given a dashboard model and seed data schema, generate TypeScript Playwright test specs.

Rules:
- Return ONLY valid TypeScript code, no prose or markdown.
- Use the GrafanaDashboardPage page object from "../../pages/grafana-dashboard.page".
- Import test constants from "../../fixtures/test-constants".
- Use absolute time ranges (SEED_FROM_EPOCH_MS, SEED_TO_EPOCH_MS), never relative.
- Assert on structure (series count, legend labels, axis presence), not exact values.
- Wait on Grafana render-complete signals, never use fixed sleeps.
- Focus on user journeys and edge cases not covered by basic panel-render tests:
  - Drill-down interactions
  - Template variable cascading
  - Tooltip hovering
  - Time range changes within the seed window
  - Panel menu interactions
  - Dashboard refresh behavior`;

export async function generateWithLlm(
  dashboard: ParsedDashboard,
  rawJson: Record<string, unknown>
): Promise<GeneratedFile[]> {
  if (!ANTHROPIC_API_KEY) {
    throw new Error(
      "ANTHROPIC_API_KEY is not set. LLM generation requires an API key."
    );
  }

  const client = new Anthropic({ apiKey: ANTHROPIC_API_KEY });

  const userPrompt = `Generate edge-case and user-journey Playwright tests for this Grafana dashboard:

Dashboard: "${dashboard.title}" (uid: ${dashboard.uid})
Panels: ${dashboard.panels.map((p) => `${p.id}: ${p.title} (${p.type})`).join(", ")}
Variables: ${dashboard.variables.map((v) => v.name).join(", ") || "none"}
Seed instances: host-a, host-b, host-c
Seed time range: 2025-01-01T00:00:00Z to 2025-01-01T06:00:00Z

Dashboard JSON excerpt:
${JSON.stringify(rawJson, null, 2).slice(0, 3000)}

Generate a single spec file with 3-5 meaningful test cases.`;

  const response = await client.messages.create({
    model: "claude-sonnet-4-20250514",
    max_tokens: 4096,
    system: SYSTEM_PROMPT,
    messages: [{ role: "user", content: userPrompt }],
  });

  // Extract text content from the response
  const textBlock = response.content.find((b) => b.type === "text");
  if (!textBlock || textBlock.type !== "text") {
    throw new Error("No text content in LLM response");
  }

  let code = textBlock.text;

  // Strip markdown code fences if present
  code = code.replace(/^```(?:typescript|ts)?\n?/m, "").replace(/\n?```$/m, "");

  const fileName = `generated/${dashboard.uid}/llm-journeys.draft.spec.ts`;

  return [
    {
      path: fileName,
      content: `/**
 * LLM-GENERATED DRAFT — requires human review before enabling.
 * Source: ${dashboard.title} (${dashboard.uid})
 * Generated by Claude. DO NOT auto-enable in the test suite.
 */

${code}
`,
    },
  ];
}
